
using Asp.Versioning;
using Microsoft.AspNetCore.Mvc;
using Rehearsal.Web.Api.Services.v1.Eulers;
using Shared.Lib.AspNetCore.Mvc;

namespace Rehearsal.Web.Api.Controllers.v1
{
    [Route("api/v{version:apiVersion}/[controller]")]
    [ApiController]
    [ApiVersion("1.0")]
    public class EulersController : ApiControllerBase
    {
        private readonly IEulerService _eulerService;

        public EulersController(IEulerService _eulerService) =>
            this._eulerService = _eulerService;

        /// <summary>
        /// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.
        /// </summary>
        /// <returns>Resultant message</returns>
        [HttpGet]
        [Route("Problem1")]
        public ActionResult Problem1()
        {
            var response = this._eulerService.SolveProblem1();

            return CreateResponse(200, response);
        }

        /// <summary>
        /// <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms.
        /// By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
        /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
        /// </summary>
        /// <returns>Sum even and sum even linq</returns>
        [HttpGet]
        [Route("Problem2")]
        public ActionResult Problem2()
        {
            var response = this._eulerService.SolveProblem2();

            return CreateResponse(200, response);
        }

        /// <summary>
        /// <p>The prime factors of 13195 are 5, 7, 13 and 29. What is the largest prime factor of the number 600851475143.
        /// </summary>
        /// <returns>T</returns>
        [HttpGet]
        [Route("Problem3")]
        public ActionResult Problem3()
        {
            var response = this._eulerService.SolveProblem3();

            return CreateResponse(200, response);
        }

        /// <summary>
        /// A palindromic number reads the same both ways.
        /// The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 x 99.
        /// Find the largest palindrome made from the product of two 3-digit numbers.
        /// </summary>
        /// <returns>T</returns>
        [HttpGet]
        [Route("Problem4")]
        public ActionResult Problem4()
        {
            var response = this._eulerService.SolveProblem4();

            return CreateResponse(200, response);
        }
    }
}
 