// <auto-generated />
using System;
using Data.Warehouse.PostgreSQL.LakeMaster.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Warehouse.PostgreSQL.LakeMaster.Migrations
{
    [DbContext(typeof(LakeMasterDbContext))]
    partial class LakeMasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DB.Models.LakeMaster.Customers.CustomerProfile", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("city")
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("dob")
                        .HasColumnType("date");

                    b.Property<string>("education")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<bool?>("email_verified")
                        .HasColumnType("boolean");

                    b.Property<string>("first_name")
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("last_name")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("martial_status")
                        .HasColumnType("text");

                    b.Property<string>("member_id")
                        .HasColumnType("text");

                    b.Property<string>("mobile_number")
                        .HasColumnType("text");

                    b.Property<string>("money_sign")
                        .HasColumnType("text");

                    b.Property<string>("ms_completed_date")
                        .HasColumnType("text");

                    b.Property<string>("pan_name")
                        .HasColumnType("text");

                    b.Property<string>("pan_no")
                        .HasColumnType("text");

                    b.Property<long?>("retirement_age")
                        .HasColumnType("bigint");

                    b.Property<Guid>("user_code")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("customer_profile");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.AboutInsurer", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("aum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<string>("ceo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("combined_ratio")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("founded_in")
                        .HasColumnType("integer");

                    b.Property<string>("gwp")
                        .HasColumnType("text");

                    b.Property<string>("headquarters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("nof_claims")
                        .HasColumnType("double precision");

                    b.Property<double?>("nof_policies")
                        .HasColumnType("double precision");

                    b.Property<string>("premium_underwritten")
                        .HasColumnType("text");

                    b.Property<long>("version")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("about_insurer", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.CategoryIP", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("category_id")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("closing_date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<long?>("distribution_method_id")
                        .HasColumnType("bigint");

                    b.Property<int?>("existing_year")
                        .HasColumnType("integer");

                    b.Property<string>("financial_year")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("logo_url")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("opening_date")
                        .HasColumnType("date");

                    b.Property<long?>("parent_category_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("plan_type_id")
                        .HasColumnType("bigint");

                    b.Property<string>("uin_code")
                        .HasColumnType("text");

                    b.Property<long>("version")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("ip_category", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.ClaimsExperienceHI", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<decimal>("ageing_of_claim")
                        .HasColumnType("numeric");

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("claim_settled_ratio")
                        .HasColumnType("numeric");

                    b.Property<decimal>("claim_settled_ratio_abs_amt")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("incurred_claim_ratio")
                        .HasColumnType("numeric");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("logo_url")
                        .HasColumnType("text");

                    b.Property<long?>("network_hospitals")
                        .HasColumnType("bigint");

                    b.Property<long>("version")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("hi_claims_experience", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.Insurance", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<double?>("accrued_bonus")
                        .HasColumnType("double precision");

                    b.Property<double?>("annual_premium")
                        .HasColumnType("double precision");

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<double?>("coverage")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("expiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("fetched_source")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_manual_entry")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("last_date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("maturity_date")
                        .HasColumnType("date");

                    b.Property<long>("months")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<long?>("payment_frequency")
                        .HasColumnType("bigint");

                    b.Property<double?>("pending_tenure")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("start_date")
                        .HasColumnType("date");

                    b.Property<Guid>("user_code")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.InsuranceCategory", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("category_id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int?>("existence_year")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("parent_category_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("category", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.InsurancePolicyEvaluation", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<double?>("accrued_bonus")
                        .HasColumnType("double precision");

                    b.Property<decimal>("annual_premium")
                        .HasColumnType("numeric");

                    b.Property<decimal>("life_cover")
                        .HasColumnType("numeric");

                    b.Property<string>("plan_category")
                        .HasColumnType("text");

                    b.Property<int?>("plan_category_id")
                        .HasColumnType("integer");

                    b.Property<string>("plan_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("plan_type_id")
                        .HasColumnType("integer");

                    b.Property<string>("policy_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("policy_start_date")
                        .HasColumnType("date");

                    b.Property<int>("policy_tenure")
                        .HasColumnType("integer");

                    b.Property<decimal>("premium_paid_till_date")
                        .HasColumnType("numeric");

                    b.Property<decimal>("premium_payable")
                        .HasColumnType("numeric");

                    b.Property<int>("premium_paying_tenure")
                        .HasColumnType("integer");

                    b.Property<int?>("scenario")
                        .HasColumnType("integer");

                    b.Property<string>("suggested_action")
                        .HasColumnType("text");

                    b.Property<string>("surrender_value")
                        .HasColumnType("text");

                    b.Property<decimal>("surrender_value_integer")
                        .HasColumnType("numeric");

                    b.Property<Guid>("user_code")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("insurance_policy_evaluation", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.InsuranceWeightage", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("parent_parameter_id")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("weightage")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("weightage", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.MaintainVersionHI", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("health_cat_id")
                        .HasColumnType("bigint");

                    b.Property<long>("hi_about_insurer")
                        .HasColumnType("bigint");

                    b.Property<long>("hi_claims_experience")
                        .HasColumnType("bigint");

                    b.Property<long>("hi_mst")
                        .HasColumnType("bigint");

                    b.Property<long>("hi_product_card")
                        .HasColumnType("bigint");

                    b.Property<long>("hi_standard_features")
                        .HasColumnType("bigint");

                    b.Property<long>("v")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("hi_maintain_version", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.MaintainVersionTI", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("term_cat_id")
                        .HasColumnType("bigint");

                    b.Property<long>("ti_about_insurer")
                        .HasColumnType("bigint");

                    b.Property<long>("ti_mst")
                        .HasColumnType("bigint");

                    b.Property<long>("ti_product_feature")
                        .HasColumnType("bigint");

                    b.Property<long>("ti_rationale")
                        .HasColumnType("bigint");

                    b.Property<long>("ti_unique_sentence")
                        .HasColumnType("bigint");

                    b.Property<long>("v")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("ti_maintain_version", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.MasterHI", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateOnly?>("as_on_date")
                        .HasColumnType("date");

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<string>("co_pay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("co_pay_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("cover_plan")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("health_and_wellness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("hw_score")
                        .HasColumnType("numeric");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("max_age")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("max_age_ff")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("min_age")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("min_age_ff")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ncb_score")
                        .HasColumnType("numeric");

                    b.Property<string>("no_claim_bonus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ped_score")
                        .HasColumnType("numeric");

                    b.Property<string>("pre_existing_disease")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("pricing_1a")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("pricing_1a_1c")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("pricing_1a_2c")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("pricing_2a")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("pricing_2a_1c")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("pricing_2a_2c")
                        .HasColumnType("numeric");

                    b.Property<string>("recharge_sum_insured")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("room_description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("room_rent_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("si_recharge_score")
                        .HasColumnType("numeric");

                    b.Property<string>("uin_code")
                        .HasColumnType("text");

                    b.Property<long>("version")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("hi_mst", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.MasterTI", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<decimal>("annual_premium")
                        .HasColumnType("numeric");

                    b.Property<decimal>("aoc_paid_from_3_to_6_mos_per")
                        .HasColumnType("numeric");

                    b.Property<decimal>("aoc_paid_from_6_to_12_mos_per")
                        .HasColumnType("numeric");

                    b.Property<decimal>("aoc_paid_less_than_3_mos_per")
                        .HasColumnType("numeric");

                    b.Property<decimal>("aoc_paid_more_than_1_yr_per")
                        .HasColumnType("numeric");

                    b.Property<decimal>("aoc_pending_eoy_per")
                        .HasColumnType("numeric");

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("claim_paid_nof_policies_per")
                        .HasColumnType("numeric");

                    b.Property<decimal>("claim_settlement_ratio_per")
                        .HasColumnType("numeric");

                    b.Property<decimal>("claimed_paid_benefit_amt_per")
                        .HasColumnType("numeric");

                    b.Property<decimal>("commission_ratio_per")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("max_age")
                        .HasColumnType("numeric");

                    b.Property<int>("max_age_at_entry")
                        .HasColumnType("integer");

                    b.Property<decimal>("max_age_at_maturity")
                        .HasColumnType("numeric");

                    b.Property<int?>("max_age_cover_for_accidental_disability")
                        .HasColumnType("integer");

                    b.Property<int?>("max_age_cover_for_ci")
                        .HasColumnType("integer");

                    b.Property<decimal>("max_policy_term")
                        .HasColumnType("numeric");

                    b.Property<string>("max_sum_assured")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("min_age")
                        .HasColumnType("numeric");

                    b.Property<string>("min_sum_assured")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("nof_claims_complaints_per_10000")
                        .HasColumnType("numeric");

                    b.Property<int?>("nof_diseases_covered_critical_illness")
                        .HasColumnType("integer");

                    b.Property<string[]>("payment_frequency")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("payout_option")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("policy_term")
                        .HasColumnType("integer");

                    b.Property<decimal>("pr_13M_by_annualized_premium_per")
                        .HasColumnType("numeric");

                    b.Property<decimal>("pr_13M_by_nof_policies_per")
                        .HasColumnType("numeric");

                    b.Property<decimal>("pr_61M_by_by_annualized_premium_per")
                        .HasColumnType("numeric");

                    b.Property<decimal>("pr_61M_by_nof_policies_per")
                        .HasColumnType("numeric");

                    b.Property<string[]>("premium_payment_options")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("rider_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("solvency_ratio")
                        .HasColumnType("numeric");

                    b.Property<decimal>("sum_assured")
                        .HasColumnType("numeric");

                    b.Property<string>("uin_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("version")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("ti_mst", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.OutputFFHI", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<decimal>("ageing_of_claim")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("aoc_score")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("avg_claims_experience_score")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("avg_product_features_score")
                        .HasColumnType("numeric");

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("claim_settled_ratio_abs_amt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("claim_settlement_ratio")
                        .HasColumnType("numeric");

                    b.Property<string>("co_pay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("co_pay_score")
                        .HasColumnType("numeric");

                    b.Property<string>("cons")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("cover_plan")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("csr_abs_amt_score")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("csr_score")
                        .HasColumnType("numeric");

                    b.Property<string>("health_and_wellness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("hi_about_insurer")
                        .HasColumnType("json");

                    b.Property<decimal>("hw_score")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("icr_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("incurred_claim_ratio")
                        .HasColumnType("numeric");

                    b.Property<string>("insurance_plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("insurer")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("logo_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("max_age")
                        .HasColumnType("numeric");

                    b.Property<decimal>("min_age")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ncb_score")
                        .HasColumnType("numeric");

                    b.Property<long?>("network_hospitals")
                        .HasColumnType("bigint");

                    b.Property<decimal>("nh_score")
                        .HasColumnType("numeric");

                    b.Property<string>("no_claim_bonus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("one_fin_rank")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("one_fin_score")
                        .HasColumnType("numeric");

                    b.Property<long?>("parent_category_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ped_score")
                        .HasColumnType("numeric");

                    b.Property<string>("pre_existing_disease")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("pricing")
                        .HasColumnType("numeric");

                    b.Property<decimal>("pricing_score")
                        .HasColumnType("numeric");

                    b.Property<string>("product_card")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pros")
                        .HasColumnType("jsonb");

                    b.Property<string>("rank_ratio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("recharge_sum_insured")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("room_description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("room_rent_score")
                        .HasColumnType("numeric");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.Property<decimal>("si_recharge_score")
                        .HasColumnType("numeric");

                    b.Property<string>("standard_feature")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<long>("total_ranking")
                        .HasColumnType("bigint");

                    b.Property<string>("uin_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("version")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("hi_output_ff", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.OutputHI", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<decimal>("ageing_of_claim")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("aoc_score")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("avg_claims_experience_score")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("avg_product_features_score")
                        .HasColumnType("numeric");

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("claim_settled_ratio_abs_amt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("claim_settlement_ratio")
                        .HasColumnType("numeric");

                    b.Property<string>("co_pay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("co_pay_score")
                        .HasColumnType("numeric");

                    b.Property<string>("cons")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("cover_plan")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("csr_abs_amt_score")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("csr_score")
                        .HasColumnType("numeric");

                    b.Property<string>("health_and_wellness")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("hi_about_insurer")
                        .HasColumnType("json");

                    b.Property<decimal>("hw_score")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("icr_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("incurred_claim_ratio")
                        .HasColumnType("numeric");

                    b.Property<string>("insurance_plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("insurer")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("logo_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("max_age")
                        .HasColumnType("numeric");

                    b.Property<decimal>("min_age")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ncb_score")
                        .HasColumnType("numeric");

                    b.Property<long?>("network_hospitals")
                        .HasColumnType("bigint");

                    b.Property<decimal>("nh_score")
                        .HasColumnType("numeric");

                    b.Property<string>("no_claim_bonus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("one_fin_rank")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("one_fin_score")
                        .HasColumnType("numeric");

                    b.Property<long?>("parent_category_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ped_score")
                        .HasColumnType("numeric");

                    b.Property<string>("pre_existing_disease")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("pricing")
                        .HasColumnType("numeric");

                    b.Property<decimal>("pricing_score")
                        .HasColumnType("numeric");

                    b.Property<string>("product_card")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pros")
                        .HasColumnType("jsonb");

                    b.Property<string>("rank_ratio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("recharge_sum_insured")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("room_description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("room_rent_score")
                        .HasColumnType("numeric");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.Property<decimal>("si_recharge_score")
                        .HasColumnType("numeric");

                    b.Property<string>("standard_feature")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<long>("total_ranking")
                        .HasColumnType("bigint");

                    b.Property<string>("uin_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("version")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("hi_output", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.OutputTI", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<decimal>("annual_premium")
                        .HasColumnType("numeric");

                    b.Property<decimal>("aoc_avg_num_and_amt_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("brand_existence_score")
                        .HasColumnType("numeric");

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("claims_experience_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("commission_ratio_score")
                        .HasColumnType("numeric");

                    b.Property<string>("cons")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("csr_nof_policies_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("csr_value_of_claims_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("death_benefit_payout_option_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("financial_ratios_score")
                        .HasColumnType("numeric");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("insurance_plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("insurer")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("logo_url")
                        .HasColumnType("text");

                    b.Property<decimal?>("max_age")
                        .HasColumnType("numeric");

                    b.Property<decimal>("max_age_cover_ci_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("max_age_cover_for_accidental_disability_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("max_maturity_age_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("min_age")
                        .HasColumnType("numeric");

                    b.Property<decimal>("nof_claims_complaints_per_10000_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("nof_diseases_covered_critical_illness_score")
                        .HasColumnType("numeric");

                    b.Property<long>("one_fin_rank")
                        .HasColumnType("bigint");

                    b.Property<decimal>("one_fin_score")
                        .HasColumnType("numeric");

                    b.Property<long?>("parent_category_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("policy_duration_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("pr_13M_by_annualized_premium_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("pr_13M_by_nof_policies_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("pr_61M_by_annualized_premium_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("pr_61M_by_nof_policies_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("premium_payment_frequency_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("premium_payment_mode_score")
                        .HasColumnType("numeric");

                    b.Property<string>("pricing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("pricing_score")
                        .HasColumnType("numeric");

                    b.Property<string>("product_features")
                        .HasColumnType("json");

                    b.Property<decimal>("product_features_score")
                        .HasColumnType("numeric");

                    b.Property<string>("pros")
                        .HasColumnType("jsonb");

                    b.Property<string>("rank_ratio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("rider_type_score")
                        .HasColumnType("numeric");

                    b.Property<int>("sequence")
                        .HasColumnType("integer");

                    b.Property<decimal>("solvency_ratio_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("sum_assured")
                        .HasColumnType("numeric");

                    b.Property<string>("ti_about_insurer")
                        .HasColumnType("json");

                    b.Property<long>("total_ranking")
                        .HasColumnType("bigint");

                    b.Property<string>("uin_code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("version")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("ti_output", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.PlanType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<long?>("category_id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("parent_type_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("plan_type", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.ProductCardHI", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("ageing_of_claim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("claim_settled_ratio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("claim_settled_ratio_abs_amt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("incurred_claim_ratio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("max_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("min_score")
                        .HasColumnType("numeric");

                    b.Property<string>("network_hospitals")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pricing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("version")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("hi_product_card", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.ProductFeatureTI", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("ageing_of_claim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("claim_payout")
                        .HasColumnType("text");

                    b.Property<string>("claim_settled")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("max_maturity_age")
                        .HasColumnType("text");

                    b.Property<decimal>("max_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("min_score")
                        .HasColumnType("numeric");

                    b.Property<string>("nof_claims_registered_per_10000")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("policy_duration")
                        .HasColumnType("text");

                    b.Property<string>("pr_13M_by_annualized_premium")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pr_13M_by_no_of_policies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("premium_payout_frequency")
                        .HasColumnType("text[]");

                    b.Property<string[]>("premium_payout_mode")
                        .HasColumnType("text[]");

                    b.Property<string>("pricing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rider_type")
                        .HasColumnType("text");

                    b.Property<string>("solvency_ratio")
                        .HasColumnType("text");

                    b.Property<long>("version")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("ti_product_feature", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.RationaleTI", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("max_age_cover_accidental_disability_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("max_age_cover_ci_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("maximum_maturity_age_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("policy_duration_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("premium_payment_frequency_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("premium_payment_option_score")
                        .HasColumnType("numeric");

                    b.Property<decimal>("rider_type_score")
                        .HasColumnType("numeric");

                    b.Property<long>("version")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("ti_rationale", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.RecommendationSummary", b =>
                {
                    b.Property<Guid>("customer_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("existing_annual_premium")
                        .HasColumnType("numeric");

                    b.Property<decimal>("existing_cover")
                        .HasColumnType("numeric");

                    b.Property<decimal>("net_savings")
                        .HasColumnType("numeric");

                    b.Property<decimal>("recommended_term_annual_premium")
                        .HasColumnType("numeric");

                    b.Property<decimal>("recommended_term_cover")
                        .HasColumnType("numeric");

                    b.HasKey("customer_code");

                    b.ToTable("ipe_recommendation_summary", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.ScenarioBasedRecommendation", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("action_rule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("applicability")
                        .HasColumnType("text");

                    b.Property<string>("based_on_suggested")
                        .HasColumnType("text");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("plan_category_description")
                        .HasColumnType("text");

                    b.Property<long>("plan_type_id")
                        .HasColumnType("bigint");

                    b.Property<string>("rationale")
                        .HasColumnType("text");

                    b.Property<string>("remark")
                        .HasColumnType("text");

                    b.Property<long>("scenario")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("scenario_based_recommendation", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.StandardFeatureHI", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("ambulance_cover")
                        .HasColumnType("text");

                    b.Property<string>("ayush_treatment")
                        .HasColumnType("text");

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("daily_allowance")
                        .HasColumnType("text");

                    b.Property<string>("daycare_treatments")
                        .HasColumnType("text");

                    b.Property<string>("domiciliary_hospitalisation")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("modern_treatment")
                        .HasColumnType("text");

                    b.Property<string>("organ_donor_cover")
                        .HasColumnType("text");

                    b.Property<string>("post_hospitalisation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pre_hospitalisation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("second_opinion")
                        .HasColumnType("text");

                    b.Property<long>("version")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("hi_standard_feature", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.Insurances.UniqueSentenceTI", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("aoc_avg_num_and_amt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<string>("commission_ratio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("csr_nof_policies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("csr_value_of_claims")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("death_benefit_payout_option")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("logo_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("max_maturity_age")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nof_claims_complaints_per_10000")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pr_13M_by_nof_policies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pr_61M_by_nof_policies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("premium_payment_frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("premium_payment_mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("solvency_ratio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("version")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("ti_unique_sentence", "insurance");
                });

            modelBuilder.Entity("DB.Models.LakeMaster.PMWells.PMWellResponse", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.Property<double>("cover")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("duration")
                        .HasColumnType("bigint");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<long?>("start_age")
                        .HasColumnType("bigint");

                    b.Property<Guid>("user_code")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("pmwell_response");
                });

            modelBuilder.Entity("Shared.Lib.Models.Category", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("guidance")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("parent_category_id")
                        .HasColumnType("bigint");

                    b.Property<string>("prescripton")
                        .HasColumnType("text");

                    b.Property<double?>("weightage")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("category");
                });
#pragma warning restore 612, 618
        }
    }
}
