// <auto-generated />
using System;
using Data.Warehouse.PostgreSQL.OSCRM.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Warehouse.PostgreSQL.OSCRM.Migrations
{
    [DbContext(typeof(OSCRMDbContext))]
    [Migration("20240519121044_FillCategoryData_Mig2")]
    partial class FillCategoryData_Mig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DB.Models.OSCRM.Customer", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("city_id")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("last_updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("middle_name")
                        .HasColumnType("text");

                    b.Property<string>("mobile_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pan_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("profession_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("city_id");

                    b.HasIndex("profession_id");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("Shared.Lib.Models.Category", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("guidance")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("parent_category_id")
                        .HasColumnType("bigint");

                    b.Property<string>("prescripton")
                        .HasColumnType("text");

                    b.Property<double?>("weightage")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("category");
                });

            modelBuilder.Entity("DB.Models.OSCRM.Customer", b =>
                {
                    b.HasOne("Shared.Lib.Models.Category", "city")
                        .WithMany()
                        .HasForeignKey("city_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Lib.Models.Category", "profession")
                        .WithMany()
                        .HasForeignKey("profession_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");

                    b.Navigation("profession");
                });
#pragma warning restore 612, 618
        }
    }
}
