<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SecretsManager" Version="3.7.302.68" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LakeMaster.Web.Api\LakeMaster.Web.Api.csproj" />
    <ProjectReference Include="..\OSCRM.Web.Api\OSCRM.Web.Api.csproj" />
    <ProjectReference Include="..\Rehearsal.Web.Api\Rehearsal.Web.Api.csproj" />
  </ItemGroup>

</Project>
